name: firebase_storage
description: dart version of https://github.com/googleapis/nodejs-storage/
version: 1.0.0

environment:
  sdk: '>=2.13.0-211.14.beta <3.0.0'

dependencies:
  http: ^0.13.3
  intl: ^0.17.0
  crypto: ^3.0.1
  rxdart: ^0.27.0
  googleapis: ^2.0.0
  googleapis_auth: ^1.1.0

dev_dependencies:
  test: ^1.17.3
  mockito: ^5.0.7
  build_runner: ^2.0.2
